<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\Handler\Response;

use Exception;

interface HandlerInterfaceException extends HandlerInterface
{
    
    /**
     * HandlerInterfaceException constructor.
     *
     * @param Exception $exception
     */
    public function __construct(Exception $exception);
    
    
    /**
     * @return string
     */
    public function message();
    
    
    /**
     * @return string
     */
    public function file();
    
    
    /**
     * @return int|mixed
     */
    public function code();
    
    
    /**
     * @return int
     */
    public function line();
    
    
    /**
     * @return string
     */
    public function traceAsString();
    
    
    /**
     * @return array
     */
    public function trace();
}
