<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\DataTransformer\Catalog\Product\Variation;

use BSeller\Api\DataTransformer\Builders;
use BSeller\Api\DataTransformer\DataTransformerAbstract;

class Create extends DataTransformerAbstract
{
    use Builders;

    /**
     * CreateVariation constructor.
     *
     * @param string $nome
     * @param int $id
     * @param array  $specifications
     */
    public function __construct($nome, $id, array $specifications = [])
    {
        $variation['nome'] = (string) $nome;
        $variation['id'] = (int) $id;

        /** Build product variation's specifications. */
        $this->buildProductSpecifications($variation, (array) $specifications);

        $this->setOutputData($variation);

        parent::__construct();
    }
}