<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\DataTransformer\Sales\Order;

use BSeller\Api\DataTransformer\Builders;
use BSeller\Api\DataTransformer\DataTransformerAbstract;
use BSeller\Api\Translation\Translatable;

class Create extends DataTransformerAbstract
{
    use Builders;
    use Translatable;

    public function __construct(
        $salesChannel,
        $shippingCustomer,
        $billingCustomer,
        $boxCode,
        $shoppingListCode,
        $salesmanCode,
        $emissionDate,
        $includingDate,
        $shipping,
        $brokenDeliveries,
        $items,
        $orderNumber,
        $externalOrderNumber,
        $storeOrderNumber,
        $tagNote,
        $orderSource,
        $payments,
        $orderForConsuming,
        $publicity,
        $freightType,
        $orderType,
        $businessUnit,
        $values
    )
    {
        $order['canalVenda'] = $salesChannel;
        $order['clienteEntrega'] = $this->translateArrayKeys($shippingCustomer, true);
        $order['clienteFaturamento'] = $this->translateArrayKeys($billingCustomer, true);
        $order['codigoBox'] = $boxCode;
        $order['codigoListaCompras'] = $shoppingListCode;
        $order['codigoVendedor'] = $salesmanCode;
        $order['dataEmissao'] = $emissionDate;
        $order['dataInclusao'] = $includingDate;
        $order['entrega'] = $this->translateArrayKeys($shipping, true);
        $order['entregasQuebradas'] = $brokenDeliveries;
        $order['itens'] = $this->translateArrayKeys($items, true);
        $order['numeroPedido'] = $orderNumber;
        $order['numeroPedidoExterno'] = $externalOrderNumber;
        $order['numeroPedidoLoja'] = $storeOrderNumber;
        $order['observacoesEtiqueta'] = $tagNote;
        $order['origemPedido'] = $orderSource;
        $order['pagamentos'] = $this->translateArrayKeys($payments, true);
        $order['pedidoParaConsumo'] = $orderForConsuming;
        $order['publicidade'] = $publicity;
        $order['tipoFrete'] = $freightType;
        $order['tipoPedido'] = $orderType;
        $order['unidadeNegocio'] = $businessUnit;
        $order['valores'] = $this->translateArrayKeys($values, true);

        $this->setOutputData($order);
        parent::__construct();
    }
}