<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../api.php';

/** @var BSeller\Api\Handler\Request\Catalog\ProductHandler $requestHandler */
$requestHandler = $api->product();

/**
 * LIST PRODUCTS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$interfaceType = 'SITE';
$maxRegisters = 100;
$pageNumber = 1;
$response = $requestHandler->products($interfaceType, $maxRegisters, $pageNumber);
$list = $response->toArray();
var_dump($list);

/**
 * LIST PRODUCTS MASSIVELLY
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$interfaceType = 'SITE';
$maxRegisters = 100;

$response = $requestHandler->productsUpdated($interfaceType, $maxRegisters);
$list = $response->toArray();
var_dump($list);
$batchNumber = $list['batchNumber'];

/**
 * CONFIRM BATCH
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
if ($batchNumber) {
    $response = $requestHandler->batch($batchNumber);
}

/**
 * GET SPECIFIC PRODUCT
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$itemCode = 'PRODUTOSEMVARIACAO01';
$interfaceType = 'SITE';
$response = $requestHandler->product($itemCode, $interfaceType);
var_dump($response->toArray());

/**
 * GET SPECIFIC PRODUCT STOCK
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$codigoItem = 'PRODUTOSEMVARIACAO01';
$tipoInterface = 'SITE';
$response = $requestHandler->stock($codigoItem, $tipoInterface);
$object = json_decode($response->body(), true);
var_dump($object);
