<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\EntityInterface;

use BSeller\Api\EntityInterface\Catalog\Product\Variation;

trait Getters
{
    
    /**
     * @return Variation
     */
    public function productVariationEntityInterface()
    {
        return new Variation($this);
    }
}
