<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../../../api.php';

/** @var BSeller\Api\Handler\Request\Sales\VoucherHandler $requestHandler */
$requestHandler = $api->voucher();

/**
 * LIST VOUCHERS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->vouchers(1);
$list = $response->toArray();
var_dump($list);exit;

/**
 * LIST PAYMENT CREDIT CARD FLAGS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->cardFlags();
$list = $response->toArray();
//var_dump($list);

/**
 * LIST PAYMENT CONDITIONS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->paymentConditions();
$list = $response->toArray();
//var_dump($list);
