<?php

namespace BSellerTest\Api;

use PHPUnit\Framework\TestCase;
use BSeller\Api;
use ReflectionClass;

/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHubTest
 * @package   SkuHubTest
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */
class ServiceTest extends TestCase
{

    /**
     * @test
     */
    public function checkServiceHttpClientInstance()
    {
        $reflection = new ReflectionClass(Api\Service\ServiceDefault::class);

        /** @var \ReflectionMethod $method */
        $method = $reflection->getMethod('httpClient');
        $method->setAccessible(true);

        $httpClient = $method->invoke(new Api\Service\ServiceDefault('http://backstg.bseller.com.br'));

        $this->assertInstanceOf(\GuzzleHttp\Client::class, $httpClient);
    }
}
