<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../../../api.php';

/** @var \BSeller\Api\EntityInterface\Sales\Order\Invoice $entityInterface */
$entityInterface = $api->invoice()
    ->entityInterface();

/**
 * APPROVE PAYMENT
 */
$orderId = '5658979804';
$transactionDate = '2018-05-04T13:10:44.000Z';
$bankCode = '123';
$agencyCode = '12349';
$accountNumber = '123456789';

$entityInterface->setOrderId($orderId)
    ->setTransactionDate($transactionDate)
    ->setBankCode($bankCode)
    ->setAgencyCode($agencyCode)
    ->setAccountNumber($accountNumber);

/**
 * SEND INVOICE TO BSELLER
 *
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $entityInterface->create();