<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../../api.php';

/** @var \BSeller\Api\Handler\Request\Catalog\Product\PriceHandler $requestHandler */
$requestHandler = $api->productPrice();

/**
 * LIST PRODUCTS PRICES
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$tipoInterface = 'SITE';
$response = $requestHandler->pricesUpdated($tipoInterface);
$list = $response->toArray();
$batchNumber = $list['batchNumber'];
//var_dump($list);

/**
 * CONFIRM BATCH
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
if ($batchNumber) {
    $response = $requestHandler->batch($batchNumber);
}
//var_dump($response->body());

/**
 * UPDATE PRODUCT PRICE
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$codigoItem = 'PRODUTOSEMVARIACAO01';
$tipoInterface = 'SITE';
$precoDe = 100;
$precoPor = 90;
$response = $requestHandler->createUpdate($codigoItem, $tipoInterface, $precoDe, $precoPor);
echo($response->body());
