<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

require_once __DIR__ .'/../vendor/autoload.php';

$authToken   = '6A9E013C42EB7152E0536AF3A8C0EDC8';

/** @var \BSeller\Api $api */
$api = new BSeller\Api($authToken);
