<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\DataTransformer;

use BSeller\Api\DataTransformer\Catalog\Product\Variation\Create;
use BSeller\Api\Helpers;

trait Builders
{
    
    use Helpers;

    /**
     * @param array $productData
     * @param array $specifications
     *
     * @return array
     */
    protected function buildProductSpecifications(array &$productData, array $specifications)
    {
        /** @var array $specification */
        foreach ($specifications as $specification) {
            $productData['variacoes'][] = $specification;
        }

        return $productData;
    }
}
