<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\DataTransformer;

abstract class DataTransformerAbstract implements DataTransformerInterface
{
    
    /** @var array */
    protected $outputData = [];
    
    
    /**
     * DataTransformerAbstract constructor.
     */
    public function __construct()
    {
    }
    
    
    /**
     * @return $this
     */
    protected function prepareOutput()
    {
        return $this;
    }
    
    
    /**
     * @param string|array $data
     *
     * @return $this
     */
    protected function setOutputData($data)
    {
        $this->outputData = $data;
        return $this;
    }
    
    
    /**
     * @return array|mixed
     */
    public function output()
    {
        $this->prepareOutput();
        return $this->outputData;
    }
}
