<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../../api.php';

/** @var \BSeller\Api\Handler\Request\Catalog\Product\StockHandler $stockHandler */
$stockHandler = $api->productStock();

/**
 * LIST PRODUCTS STOCKS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $stockHandler->stocksUpdated();
$list = $response->toArray();
var_dump($list);
$batchNumber = $list['batchNumber'];

/**
 * CONFIRM BATCH
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
if ($batchNumber) {
    $response = $requestHandler->batch($batchNumber);
}
var_dump($response->body());

/**
 * GET PRODUCT STOCK
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$productCode = 'PRODUTOSEMVARIACAO01';
$tipoInterface = 'SITE';
$response = $stockHandler->stock($productCode, $tipoInterface);
$list = $response->toArray();
var_dump($list);
