<?php
/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform.
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

include __DIR__ . '/../../api.php';

/** @var BSeller\Api\Handler\Request\Sales\CarrierHandler $requestHandler */
$requestHandler = $api->carrier();

/**
 * LIST CARRIERS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
//$response = $requestHandler->carriers();
//$list = $response->toArray();
//var_dump($list);
//exit;

/**
 * LIST CONTRACTS
 * @var BSeller\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->contracts('34028316002823');
$list = $response->toArray();
var_dump($list);
exit;