<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\Handler\Request;

use BSeller\Api\Handler\Request\Catalog\CategoryHandler;
use BSeller\Api\Handler\Request\Catalog\Product\AttributeHandler;
use BSeller\Api\Handler\Request\Catalog\ProductHandler;
use BSeller\Api\Handler\Request\Sales\Order\QueueHandler;
use BSeller\Api\Handler\Request\Sales\Order\StatusHandler;
use BSeller\Api\Handler\Request\Sales\OrderHandler;
use BSeller\Api\Handler\Request\Sales\SystemHandler;
use BSeller\Api\Handler\Request\Sync\ErrorsHandler;
use BSeller\Api\Handler\Request\Catalog\Product\VariationHandler;

trait Getters
{

    /**
     * @return AttributeHandler
     */
    public function productAttribute()
    {
        return new AttributeHandler($this);
    }


    /**
     * @return ProductHandler
     */
    public function product()
    {
        return new ProductHandler($this);
    }


    /**
     * @return VariationHandler
     */
    public function productVariations()
    {
        return new VariationHandler($this);
    }


    /**
     * @return CategoryHandler
     */
    public function category()
    {
        return new CategoryHandler($this);
    }


    /**
     * @return QueueHandler
     */
    public function queue()
    {
        return new QueueHandler($this);
    }


    /**
     * @return OrderHandler
     */
    public function order()
    {
        return new OrderHandler($this);
    }


    /**
     * @return StatusHandler
     */
    public function orderStatus()
    {
        return new StatusHandler($this);
    }


    /**
     * @return SystemHandler
     */
    public function saleSystems()
    {
        return new SystemHandler($this);
    }


    /**
     * @return ErrorsHandler
     */
    public function syncErrors()
    {
        return new ErrorsHandler($this);
    }
}
