<?php

/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\Handler\Request\Catalog\Product;

use BSeller\Api\Handler\Request\HandlerAbstract;
use BSeller\Api\Handler\Response\HandlerInterface;

class CategoryHandler extends HandlerAbstract
{

    /** @var string */
    protected $baseUrlPath = '/api/itens/categorias';

    /**
     * @return HandlerInterface
     */
    public function categories($tipoInterface = null)
    {
        $params = [];
        if ($tipoInterface) {
            $params = [
                'tipoInterface' => $tipoInterface,
            ];
        }

        /** @var HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath(null, $params));
        return $responseHandler;
    }

    /**
     * @return null
     */
    public function entityInterface()
    {
        return null;
    }
}
