<?php

/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller\Api\Handler\Request\Catalog\Product;

use BSeller\Api\Handler\Request\HandlerAbstract;
use BSeller\Api\Handler\Response\HandlerInterface;

class PriceHandler extends HandlerAbstract
{

    /** @var string */
    protected $baseUrlPath = '/api/itens/precos';

    /**
     * @param null $tipoInterface
     * @param null $maxRegisters
     * @return HandlerInterface
     */
    public function pricesUpdated($tipoInterface = null, $maxRegisters = null)
    {
        $params = [];
        if ($tipoInterface) {
            $params['tipoInterface'] = $tipoInterface;
        }

        if ($maxRegisters) {
            $params['maxRegistros'] = $maxRegisters;
        }

        /** @var HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath(null, $params));
        return $responseHandler;
    }

    /**
     * @param $codigoItem
     * @param $tipoInterface
     * @param $precoDe
     * @param $precoPor
     * @return HandlerInterface
     */
    public function createUpdate(
        $codigoItem,
        $tipoInterface,
        $precoDe,
        $precoPor
    )
    {
        $params = [];
        $params['precoDe'] = $precoDe;
        $params['precoPor'] = $precoPor;

        /** @var \BSeller\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->put($this->baseUrlPath("{$codigoItem}/{$tipoInterface}"), $params);
        return $responseHandler;
    }

    /**
     * @return null
     */
    public function entityInterface()
    {
        return null;
    }
}
