<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  BSeller
 * @package   BSeller
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools Platform. .
 *
 * @author    Julio Reis <julio.reis@b2wdigital.com>
 */

namespace BSeller;

use BSeller\Api\Service\ServiceInterface;

interface ApiInterface
{

    /**
     * ApiInterface constructor.
     *
     * @param string                $authToken
     * @param string|null           $baseUri
     * @param ServiceInterface|null $apiService
     */
    public function __construct(
        $authToken,
        $baseUri = null,
        ServiceInterface $apiService = null
    );
    
    
    /**
     * @return \BSeller\Api\Service\ServiceInterface
     */
    public function service();
}
